#!/bin/bash
echo "📱 TORC Mobile App - Access Options"
echo "===================================="
echo ""
echo "Option 1: Browser (Quick Test)"
echo "  → http://localhost:8081"
echo ""
echo "Option 2: Expo Go on Phone"
echo "  1. Install 'Expo Go' app from App Store/Play Store"
echo "  2. Open Expo Go app"
echo "  3. Tap 'Enter URL manually'"
echo "  4. Enter: exp://$(ipconfig getifaddr en0):8081"
echo ""
echo "Option 3: iOS Simulator"
echo "  Press 'i' in the terminal where npm start is running"
echo ""
echo "Option 4: Android Emulator"
echo "  Press 'a' in the terminal where npm start is running"
echo ""
echo "✅ Metro bundler is running on port 8081"
